project:
  type: website
  output-dir: _site
  render:
    -  "*.qmd"
    - "!area_51.qmd"
execute:
  freeze: auto

website:
  title: "Core statistics"
  description: "Supporting materials for the Core statistics course (University of Cambridge)"
  site-url: https://cambiotraining.github.io/corestats/
  repo-url: https://github.com/cambiotraining/corestats
  repo-actions: [issue]
  page-navigation: true
  favicon: "images/favicon.ico"
  page-footer:
    left: |
      [Bioinformatics Training Facility](https://bioinfotraining.bio.cam.ac.uk)
    right:
      - icon: github
        href: https://github.com/cambiotraining/
        aria-label: Bioinformatics Training Facility GitHub

  navbar:
    background: primary
    pinned: true
    logo: "images/university_crest_reversed.png"
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Simple hypothesis testing"
        contents:
          - cs1_practical_one-sample-t-test.qmd
          - cs1_practical_one-sample-wilcoxon.qmd
          - cs1_practical_two-sample-t-test.qmd
          - cs1_practical_two-sample-mann-whitney.qmd
          - cs1_practical_two-sample-paired-t-test.qmd
          - cs1_practical_two-sample-paired-wilcoxon.qmd
      - section: "Categorical predictors"
        contents:
          - cs2_practical_anova.qmd
          - cs2_practical_kruskal-wallis.qmd
      - section: "Continuous predictors"
        contents:
          - cs3_practical_linear-regression.qmd
          - cs3_practical_correlations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

